// Generated by ReScript, PLEASE EDIT WITH CARE


let Document = {};

let Window = {};

let Local = {};

let Storage = {
  Local: Local
};

let Runtime = {};

let Chrome = {
  Storage: Storage,
  Runtime: Runtime
};

let state = {
  isActive: false,
  isBypassed: false,
  preset: "auto",
  targetLufs: -14.0,
  inputLevel: -120.0,
  outputLevel: -120.0
};

let presets = [
  {
    name: "auto",
    targetLufs: -14.0,
    compressionRatio: 4.0,
    noiseReduction: true
  },
  {
    name: "speech",
    targetLufs: -16.0,
    compressionRatio: 3.0,
    noiseReduction: true
  },
  {
    name: "music",
    targetLufs: -14.0,
    compressionRatio: 2.0,
    noiseReduction: false
  },
  {
    name: "night",
    targetLufs: -20.0,
    compressionRatio: 6.0,
    noiseReduction: true
  },
  {
    name: "hearing",
    targetLufs: -12.0,
    compressionRatio: 4.0,
    noiseReduction: true
  }
];

function handleMessage(message) {
  
}

function init() {
  chrome.storage.local.get(["volumod_settings"], settings => {});
}

function saveSettings() {
  let settings = {
    isBypassed: state.isBypassed,
    preset: state.preset,
    targetLufs: state.targetLufs
  };
  chrome.storage.local.set({
    volumod_settings: settings
  }, () => {});
}

function toggleBypass() {
  state.isBypassed = !state.isBypassed;
  saveSettings();
}

function setPreset(presetName) {
  state.preset = presetName;
  let presetOpt = presets.find(p => p.name === presetName);
  if (presetOpt !== undefined) {
    state.targetLufs = presetOpt.targetLufs;
    return saveSettings();
  }
}

let ui = {
  bypassButton: null,
  presetSelect: null,
  levelMeter: null,
  statusText: null
};

function initUI() {
  ui.bypassButton = document.getElementById("bypass-btn");
  ui.presetSelect = document.getElementById("preset-select");
  ui.levelMeter = document.getElementById("level-meter");
  ui.statusText = document.getElementById("status-text");
}

function updateUI() {
  
}

let PopupUI = {
  ui: ui,
  initUI: initUI,
  updateUI: updateUI
};

function announce(message, priority) {
  document.createElement("div");
}

function formatLevelForSpeech(db) {
  if (db < -60.0) {
    return "silent";
  } else if (db < -40.0) {
    return "very quiet";
  } else if (db < -20.0) {
    return "quiet";
  } else if (db < -10.0) {
    return "moderate";
  } else if (db < -3.0) {
    return "loud";
  } else {
    return "very loud";
  }
}

let Accessibility = {
  announce: announce,
  formatLevelForSpeech: formatLevelForSpeech
};

window.addEventListener("DOMContentLoaded", param => init());

export {
  Document,
  Window,
  Chrome,
  state,
  presets,
  handleMessage,
  init,
  saveSettings,
  toggleBypass,
  setPreset,
  PopupUI,
  Accessibility,
}
/*  Not a pure module */
